#!/bin/bash
# ============================================================
# JBWizerd Panel — Docker entrypoint
#
# 1. Generates includes/config.php from environment variables
#    (only if it does not already exist — setup.php can override).
# 2. Installs the cron jobs (webhook sender every minute,
#    retention cleanup daily at 03:00).
# 3. Starts Apache in the foreground.
# ============================================================

set -e

CONFIG_FILE="/var/www/html/includes/config.php"

if [ ! -f "$CONFIG_FILE" ]; then
  echo "==> Generating includes/config.php from environment ..."

  cat > "$CONFIG_FILE" <<PHP
<?php
// JBWizerd Panel - Configuration (generated by Docker)

ini_set('display_errors', '0');
error_reporting(E_ALL);

define('BRAND_NAME', 'JBWizerd');

define('TIMEZONE', '${JBWIZERD_TIMEZONE:-Asia/Dhaka}');

define('DB_HOST', '${JBWIZERD_DB_HOST:-db}');
define('DB_NAME', '${JBWIZERD_DB_NAME:-jbwizerd}');
define('DB_USER', '${JBWIZERD_DB_USER:-jbuser}');
define('DB_PASS', '${JBWIZERD_DB_PASS:-jbpass}');

define('DB_CHARSET', 'utf8mb4');

define('PANEL_URL', '${JBWIZERD_PANEL_URL:-http://localhost:8080}');

define('REGISTRATION_KEY', '${JBWIZERD_REGISTRATION_KEY}');

define('RETENTION_DAYS', ${JBWIZERD_RETENTION_DAYS:-365});
define('WEBHOOK_LOG_RETENTION_DAYS', ${JBWIZERD_WEBHOOK_LOG_RETENTION_DAYS:-90});
define('AUDIT_LOG_RETENTION_DAYS', ${JBWIZERD_AUDIT_LOG_RETENTION_DAYS:-90});

define('WEBHOOK_MAX_ATTEMPTS', ${JBWIZERD_WEBHOOK_MAX_ATTEMPTS:-5});
define('CONNECTED_WINDOW_HOURS', ${JBWIZERD_CONNECTED_WINDOW_HOURS:-48});

define('SESSION_NAME', 'jbpanel_session');
define('SESSION_LIFETIME', ${JBWIZERD_SESSION_LIFETIME:-7200});

define('LOGIN_MAX_ATTEMPTS', ${JBWIZERD_LOGIN_MAX_ATTEMPTS:-5});
define('LOGIN_LOCKOUT_WINDOW', ${JBWIZERD_LOGIN_LOCKOUT_WINDOW:-900});

define('REGISTER_MAX_PER_HOUR', ${JBWIZERD_REGISTER_MAX_PER_HOUR:-10});
define('STUCK_BACKUP_HOURS', ${JBWIZERD_STUCK_BACKUP_HOURS:-24});

define('TRUSTED_PROXIES', '');
PHP

  chown www-data:www-data "$CONFIG_FILE"
  chmod 600 "$CONFIG_FILE"
  echo "==> config.php written."
else
  echo "==> includes/config.php already exists — leaving it untouched."
fi

# Ensure cron status file is writable
mkdir -p /var/www/html/cron
touch /var/www/html/cron/cron-status.json
chown -R www-data:www-data /var/www/html/cron

# --- Cron jobs ---
# Webhook sender every minute; retention cleanup daily at 03:00.
echo "==> Installing cron jobs ..."
cat > /etc/cron.d/jbwizerd <<CRON
* * * * * www-data /usr/local/bin/php /var/www/html/cron/send-webhooks.php > /dev/null 2>&1
0 3 * * * www-data /usr/local/bin/php /var/www/html/cron/cleanup.php > /dev/null 2>&1
CRON
chmod 0644 /etc/cron.d/jbwizerd
crontab -u www-data /etc/cron.d/jbwizerd 2>/dev/null || true
cron

echo "==> Starting Apache ..."
exec "$@"
